server:
  port: 8080


spring:
  application:
    name: customer
  datasource:
    username: 'root'
    url: jdbc:mysql://localhost:3306/customer
    password: 'Ashihundu@2003'
    jpa:
        properties:
          hibernate:
            dialect:
            format_sql: 'true'
        hibernate:
          ddl-auto: update
        show-sql: 'true'